### ISSUE TITLE
SmartPtr does not name a type

### ISSUE THREAD

**Issue by Crozin** [PocketRent/hhvm-pgsql#97]
Server configuration:

    # lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 8.1 (jessie)
    Release:        8.1
    Codename:       jessie
    
    # hhvm --version
    HipHop VM 3.7.3 (rel)
    Compiler: tags/HHVM-3.7.3-0-g08c64d25f6c2cd316730b1d37db9eb33744cb306
    Repo schema: 6ba408ef27e1fc7820c8bd6352989f40c1acb812

When I'm trying to complie the following error occurs:

    # hphpize && cmake . && make
    ** hphpize complete, now run `cmake . && make` to build, `make test` to test
    -- The C compiler identification is GNU 4.9.2
    -- The CXX compiler identification is GNU 4.9.2
    -- The ASM compiler identification is GNU
    -- Found assembler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Configuring for HHVM API version 20150212
    -- pgSQL Include dir: /usr/include/postgresql
    -- libpq library: /usr/lib/x86_64-linux-gnu/libpq.so
    CMake Warning (dev) at CMakeLists.txt:42 (add_custom_target):
      Policy CMP0037 is not set: Target names should not be reserved and should
      match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.

      The target name "test" is reserved or not valid for certain CMake features,
      such as generator expressions, and may result in undefined behavior.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /root/tmp/hhvm-pgsql
    Scanning dependencies of target pgsql
    [ 25%] Building CXX object CMakeFiles/pgsql.dir/pgsql.cpp.o
    [ 50%] Building CXX object CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o
    In file included from /root/tmp/hhvm-pgsql/pdo_pgsql_statement.cpp:4:0:
    /root/tmp/hhvm-pgsql/pdo_pgsql.h:10:13: error: ‘SmartPtr’ does not name a type
         virtual SmartPtr<PDOResource> createResourceImpl() override;
                 ^
    /root/tmp/hhvm-pgsql/pdo_pgsql.h:11:13: error: ‘SmartPtr’ does not name a type
         virtual SmartPtr<PDOResource> createResourceImpl(const sp_PDOConnection& conn) override;
                 ^
    CMakeFiles/pgsql.dir/build.make:77: recipe for target 'CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o' failed
    make[2]: *** [CMakeFiles/pgsql.dir/pdo_pgsql_statement.cpp.o] Error 1
    CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pgsql.dir/all' failed
    make[1]: *** [CMakeFiles/pgsql.dir/all] Error 2
    Makefile:117: recipe for target 'all' failed
    make: *** [all] Error 2

---

Of course I've tried precomiled SO file, but then I'm getting following error:

    php: symbol lookup error: /etc/hhvm/pgsql.so: undefined symbol: _ZNK4HPHP9ArrayData6existsEl

I've already tried installing nighlty-builds but they produce the very same error.

**Comment by fadimko** [comment]
Up.
This seems to solve the problem #93

**Comment by Aatch** [comment]
Fixed by 160fa5c

**Comment by eugene-dounar** [comment]
Still having this error on HHVM 3.10 and hhvm-pgsql 3.10.0 
[This commit](https://github.com/rny/hhvm-pgsql/commit/56b165ba62724ef38963c34a435e7eff8d54016f) still solves the issue
